import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import SideMenu from "@/components/SideMenu";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-black text-white ">
      <body className={inter.className}>
        <div className="border-b ">
          <div className="flex h-16 items-center px-4">
            <Image
              src="/Album.png"
              alt="Album icon"
              width="60"
              height="60"
              className="mr-4"
            />
            PHOTOS APP
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage
                  src="https://github.com/shadcn.png"
                  alt="@shadcn"
                />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-[20%,80%]">
          <SideMenu />
          <div className="w-full pr-8 pt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
